#!/bin/bash

# .gitignore helper
# a simple script which removes the manual labour of adding the
# files/directories to .gitignore

check_if_git=$(git rev-parse --is-inside-work-tree)
check_if_git_exit_code=$(echo $?)

num_args=$(echo $#)

if [[ num_args -eq 0 ]]; then
	echo "Error : No arguments given" >&2
	exit 1
fi

if [[ check_if_git_exit_code -ne 0 ]]; then
	exit $check_if_git_exit_code
fi

git_root_path=$(git rev-parse --show-toplevel)
gitignore_path="$git_root_path/.gitignore"

# realpath -s --relative-to="$git_root_path" $(pwd)

for arg in "$@"; do
	if [[ -f $arg ]]; then
		relative_path=$(realpath -s --relative-to="$git_root_path" $arg)
		echo $relative_path >>"$gitignore_path"
	elif [[ -d $arg ]]; then
		relative_path=$(realpath -s --relative-to="$git_root_path" $arg)
		echo "$relative_path/" >>"$gitignore_path"
	fi
done
